### ISSUE TITLE
Tek Grinder

### ISSUE THREAD

**Issue by iMasonite** [iMasonite/KenetiCommunityMod#22]
Because cool things can happen here...

**Comment by iMasonite** [comment]
Added Tek Grinder 


![Image](https://github.com/iMasonite/KenetiCommunityMod/assets/4611812/cca65667-5c49-4283-ba0a-05ec5b78652f)

**Comment by noxidevad** [comment]
How does this fair compared to original grinder? 

Example do we receive a higher return % per item and/or are we able to turn stone into flint with a high slot cap than 1000 at a time? 

Loving these new qol

**Comment by iMasonite** [comment]
## Grinding 
| Structure | Return Percent | MaxItemsToGivePerGrind
| ------------- | ------------- | ------------- | 
| Normal Grinder  | 30% | 150 |
| Tek Grinder | 50% | 2000 |

> [!NOTE]
> MaxItemsToGivePerGrind = how many resources that will be returned per resource type per ground item. 

## Crafting (Vanilla Grinder)
| Craft Item | Requires Item | Crafts Quantity
| ------------- | ------------- | -------------
| Flint  | Stone x2 | 1
| Thatch | Wood x1 | 5

## Crafting (TekGrinder)
| Craft Item | Requires Item | Crafts Quantity
| ------------- | ------------- | -------------
| Flint  | Stone x2 | 3
| Thatch | Wood x1 | 7
| Bio Toxin | Narcotic x50 | 2
| Hard Polymer| Organic Polymer x9, Paste x10 | 8
