### ISSUE TITLE
Alpha Unicorn - No drop shown bug

### ISSUE THREAD

**Issue by noxidevad** [iMasonite/KenetiCommunityMod#23]
![carryalpha](https://github.com/iMasonite/KenetiCommunityMod/assets/54919614/86a3ef8f-9a90-4e02-ad12-3980a4bb8d94)
![noptear2](https://github.com/iMasonite/KenetiCommunityMod/assets/54919614/50fdcf53-a678-4f70-bac1-97f2a4abad49)
![notearshown](https://github.com/iMasonite/KenetiCommunityMod/assets/54919614/69a8ee68-e898-4599-8d3f-9bf215906b0d)

Added images to show (the individual tears, currently do no show when trying to collect, you're able to pick up them up providing you can find the hitbox, but physically you can't see them at the minute) as for the poop you can see it, however sometimes it looks like it's half sunk underground.

second part of alpha unicorn, as it's an alpha i was under the impression we should be unable to pick them up? 

Can't add any tags as unsure if this is for you to assign yourself.

**Comment by noxidevad** [comment]
![yellowhorn](https://github.com/iMasonite/KenetiCommunityMod/assets/54919614/bcab7ee9-5351-4e47-acb7-4ab1c61153a8)
![yellowhorn1](https://github.com/iMasonite/KenetiCommunityMod/assets/54919614/b85bc9c6-e8f5-4b35-ae77-7768c2daa53f)
![yellowtear](https://github.com/iMasonite/KenetiCommunityMod/assets/54919614/893179f3-553d-46b7-a41d-d5c719efcf3e)

Just another update, so decided to move it into my base just to experiment. In certain areas of my breeding area (see images) the unicorn is actually dropping it tears, even though its on structures so another bug to look into

**Comment by iMasonite** [comment]
Increased the dropped tear pick-up all range (when F key is pressed) to 600 from 275. this should allow picking up of tears partially stuck in the mesh. (testing on live will be required ofc)

**Comment by iMasonite** [comment]
- Alpha Unicorn Tear dropped item size is now 2x what it was previously.
- Alpha Unicorn Tear slightly floats above the terrain.

- Unchecked 'Can be Carried' in Alpha Unicorn BP, high drag-weight is no longer sufficient.
