### ISSUE TITLE
Industrial Cooker - Wireless Crafting

### ISSUE THREAD

**Issue by noxidevad** [iMasonite/KenetiCommunityMod#26]
Now that we can pull items from dedicated storage into stuff like replicator, console, chemistry bench. I know you spoke briefly about having stuff like this to help with storage. 

Currently the Industrial Cooker will not pull items from dedicated storage at some point down the line. With your many to do tasks currently, could we potentially have this feature in the future.

**Comment by iMasonite** [comment]
This is not currently possible with the auto crafting system after many attempts at a work around without adverse effects on the crafting of other resources. A new crafting station with non auto crafting may be added or with additional logic outside of the vanilla structures on a non vanilla structure.
