### ISSUE TITLE
kc dedi storage

### ISSUE THREAD

**Issue by CLEEVSEY** [iMasonite/KenetiCommunityMod#29]
when they are destroyed the dropped loot bags have no way of looting

![image](https://github.com/iMasonite/KenetiCommunityMod/assets/155453728/347b6ada-4860-4ff9-a60f-35ca546a62c8)

![image](https://github.com/iMasonite/KenetiCommunityMod/assets/155453728/317eb80a-9441-4954-aac3-16cded611d26)

**Comment by iMasonite** [comment]
Unable to get items to show in the inventory space like an ordinary drop item container without causing it to lose items. 

As usual though, like a Dedicated Storage inventory, clicking double arrows (Take All) will collect all items into the players inventory untill the players inventory is full (or encumbered in some cases). Rinse and repeat as many times as required to empty the item cache. 

Note:
> The issue here is that the two types of `Structure Item Container` use different methods to store items, one uses actual items in an array of `PrimalItem` (most containers) and the other (in the case of the Dedicated Storage) uses _Item Count_ where the actual items are stored as an `Integer` value. 

> If the Dedicated Storage Item Cache inventory quantity exceeds the maximum capacity of a regular Dropped Item Cache the the remaining items are yeeted into oblivion.

Like in the screenshot given, it can be seen how many items will be given when the double arrows (Take All) will be given to the players inventory. In this case, 889 Medical Brews.
![Image](https://github.com/user-attachments/assets/2af3b5f4-0d94-449b-a5b8-e2abcfb52c62)
